 uglifyjs --beautify --compress \
 ../js/libs/angular/angular.js \
 ../js/libs/angular/angular-cookies.js \
 ../js/libs/angular/angular-route.js \
 ../js/libs/angular/angular-file-upload.js \
 ../js/libs/angular/angular-color-picker.js \
 ../js/libs/jquery.js \
 ../js/config.js \
 ../js/route.js \
 ../js/contentController.js \
 ../js/controller/login.js \
 ../js/controller/logout.js \
 ../js/controller/account.js \
 ../js/controller/welcome.js \
 ../js/controller/register.js \
 ../js/controller/cardCreate.js \
 ../js/controller/cardList.js \
 ../js/controller/cardDetail.js \
 ../js/controller/accountUpdate.js \
 ../js/controller/cardUpdate.js \
 ../js/controller/templateList.js \
 ../js/controller/templateCreate.js \
 ../js/controller/templateDelete.js \
 ../js/controller/cardDelete.js \
 ../js/controller/collectionList.js \
 ../js/controller/collectionDelete.js \
 ../js/controller/contactList.js \
 ../js/controller/collectionMapCard.js \
 ../js/controller/reportBug.js \
 ../js/app.js \
 -o test_000002.js